FROM golang:1.21.11 AS orig-cli
WORKDIR /

FROM debian
RUN apt-get update && apt-get install -y git curl bash jq

RUN curl -L https://foundry.paradigm.xyz | bash
RUN bash -c 'source /root/.profile && foundryup'
RUN cp -r /root/.foundry/bin/* /usr/local/bin/
RUN adduser --uid 1000 foundry
RUN curl -sSfL https://raw.githubusercontent.com/layr-labs/eigenlayer-cli/master/scripts/install.sh | sh -s -- v0.11.0
RUN mv /root/bin/eigenlayer /usr/local/bin/eigenlayer-orig
RUN curl -sSfL https://raw.githubusercontent.com/layr-labs/eigenlayer-cli/master/scripts/install.sh | sh -s -- v0.12.0-beta
RUN mv /root/bin/eigenlayer /usr/local/bin/eigenlayer-holesky

ENTRYPOINT ["/bin/sh", "-c"]