FROM rust:latest

WORKDIR /usr/src/setup-operator
COPY ./setup-operator /usr/src/setup-operator

CMD ["bash", "-c", "cargo run --bin setup-operator -- --operator-private-key 0xc276a0e2815b89e9a3d8b64cb5d745d5b4f6b84531306c97aad82156000a7dd7 --http-endpoint http://anvil:8545 --strategy-deposit-address 0x09635F643e140090A9A8Dcd712eD6285858ceBef --strategy-deposit-amount 10 --chain-writer-reader-addresses contracts/script/input/deployment_parameters_devnet.json --avs-registry-writer-addresses contracts/script/output/coprocessor_deployment_output_devnet.json"]