FROM golang:1.21.11 AS orig-cli
WORKDIR /

FROM debian
RUN apt-get update && apt-get install -y git curl bash jq

RUN curl -L https://foundry.paradigm.xyz | bash
RUN bash -c 'source /root/.profile && foundryup'
RUN cp -r /root/.foundry/bin/* /usr/local/bin/
RUN adduser --uid 1000 foundry
COPY ./env/eigenlayer/anvil/avs-and-eigenlayer-deployed-anvil-state.json /root/.anvil/state.json
COPY ./env/eigenlayer/anvil/run-anvil-devnet.sh /run-anvil-devnet.sh

ENTRYPOINT ["/bin/sh", "-c"]